[global]
; 애플리케이션 글로벌 설정
MAX_RETRY                      = 5           ; 영상 수신 실패 시 최대 재시도 횟수
MIN_SKIP_FRAME                 = 1           ; 최소 스킵 프레임 수
DANGER_MAINTAIN_TIME           = 5           ; 위험 상태 유지 시간 (초)
JIGUK_DANGER_MAINTAIN_TIME     = 2.0         ; 지적확인 위험 상태 유지 시간 (초)
BULTI_DANGER_MAINTAIN_TIME     = 5.0         ; 불티비산(훈소) 위험 상태 유지 시간 (초)
COLLISION_DANGER_MAINTAIN_TIME = 3.0         ; 접근 감지 위험 상태 유지 시간 (초)
RECORD_DURATION                = 5           ; 이벤트로그 작성 시 영상 저장 시간 (초)
SEQUENCE_BUFFER_SIZE           = 30          ; 연속 검출 시 프레임 데이터 저장용 deque 크기 (프레임 수)
JIGUK_BUFFER_SIZE              = 30          ; 연속 검출 시 지적확인 행동 검출 여부 저장용 deque 크기 (프레임 수)
TRACKER_MAX_ID_COUNT           = 1000        ; YOLO Tracker에 저장할 최대 ID 카운트
MAX_RECORD_BUFFER_SIZE         = 90          ; 녹화 시 최대 프레임 버퍼 크기 (프레임 수)
ROI_EXTEND_PIXEL               = 50          ; ROI 확장 픽셀 수
SYSTEM_CHECK_TIME              = 60          ; 시스템 상태 점검 주기 (초)
TRACKER_RESET_HOUR             = 0           ; TRACKER ID 리셋 시각 (시)
TRACKER_RESET_MINUTE           = 0           ; TRACKER ID 리셋 시각 (분)
LINE_WIDTH                     = 1           ; BBOX 시각화 선 두께
DANGER_INDICATOR_CIRCLE_MODE   = True        ; 위험 인디케이터 모드 (원형: True, 사각형: False)
DANGER_INDICATOR_LOCATION      = (610, 30)   ; 위험 인디케이터 위치
DANGER_INDICATOR_RADIUS        = 20          ; 위험 인디케이터 반지름

[logic_list]
거리 = is_bbox_close
크기 = is_bbox_large
화재 = detect_fire
테스트용 = test_function
지적확인1 = jiguk1
지적확인2 = jiguk2
지적확인3 = jiguk3
불티비산 = bulti
접근감지 = detect_collision
안전대&안전벨트1 = safebelt1
안전대&안전벨트2 = safebelt2
보호구감지 = flash_suit
월담감지 = waldam
쓰러짐감지 = falldown
작업자 카운트 = person_count

[session]
; 지적확인 진입-대기-이탈 세션 관련 설정
LEAVE_GRACE_SEC = 0.6                     ; 이탈 대기 시간 (초)
COOLDOWN_SEC    = 2.0                     ; 세션 종료 후 동일 ID 재진입 쿨다운 (초)
MIN_DWELL_SEC   = 10.0                    ; 지적확인 개소 내 n초 이상 체류 시 무시 (초)
MIN_MOVE_PX     = 5                       ; 방향성 판단 최소 이동 픽셀 (px)

[bulti]
ROI_EXTEND_PIXEL = 100                    ; ROI 확장 픽셀 수 (px)
ROI_MAINTAIN_TIME = 600                   ; ROI 유지 시간 (초)

[collision]
; 접근 감지 관련 설정
ROI_EXTEND_PIXEL     = 50                 ; ROI 확장 픽셀 수 (px)
MIN_COLLISION_FRAMES = 2                  ; 최소 충돌 프레임 수 (int)
MAX_WINDOW_FRAMES    = 10                 ; 최대 윈도우 프레임 수 (px)

[safebelt]
; 안전대&안전벨트 관련 설정
ROI_EXTEND_PIXEL    = 100                 ; ROI 확장 픽셀 수 (px)
LOGIC_1_DETECT_TIME = 2                   ; 안전대&안전벨트 로직 1 감지 시간 조절용 deque size 설정 (초) -> (영상 FPS / 스킵 프레임) * 감지 시간 = 실제 deque 크기 계산
LOGIC_2_DETECT_TIME = 2                   ; 안전대&안전벨트 로직 2 감지 시간 조절용 deque size 설정 (초) -> (영상 FPS / 스킵 프레임) * 감지 시간 = 실제 deque 크기 계산

[flash_suit]
; 방염복 관련 설정
ROI_EXTEND_PIXEL = 100                    ; ROI 확장 픽셀 수 (px)
DETECT_TIME      = 2                      ; 방염복 감지 시간 조절용 deque size 설정 (초) -> (영상 FPS / 스킵 프레임) * 감지 시간 = 실제 deque 크기 계산

[waldam]
; 월담 감지 관련 설정

[falldown]
; 쓰러짐 감지 관련 설정

[자동 정리 설정]
required_capacity = 200
delete_capacity   = 100